name: pygeo
channels:
  - conda-forge
  - esri
dependencies:
  - python=3.6
  - arcgis
  - gdal
  - imageio
  - matplotlib
  - numpy
  - scikit-image
  - scikit-learn
  - scipy
  - pip:
    - bokeh
    - cython
    - descartes
    - descartes
    - folium
    - geojsonio
    - geopandas
    - h5py
    - lidar
    - mapboxgl
    - pandana
    - plotly
    - pygdal
    - pygis
    - pyModis
    - pysal
    - rasterio
    - rasterstats
    - requests
    - rtree
    - seaborn
    - sentinelhub
    - tifffile
    - whitebox
    - xarray
    - tensorflow
    - keras